name: Sync and Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

permissions:
  contents: write
  pages: write
  id-token: write
  gists: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Gist Data
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GIST_ID: "df6ceeb52f594b01a16495b214d93af0"
        run: |
          curl -s -H "Authorization: token $GH_TOKEN" \
               "https://api.github.com/gists/$GIST_ID" | \
          jq -r '.files."patrimonios.json".content' > patrimonios.json

      - name: Deploy
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add patrimonios.json
          git commit -m "Update data" || exit 0
          git push
