name: Deploy with Gist Sync

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

permissions:
  contents: write
  pages: write
  id-token: write
  gists: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Gist Data
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GIST_ID: "df6ceeb52f594b01a16495b214d93af0"
        run: |
          mkdir -p public
          curl -s -H "Authorization: token $GH_TOKEN" \
               "https://api.github.com/gists/$GIST_ID" | \
          jq -r '.files."patrimonios.json".content' > public/patrimonios.json

          # Verificação
          [ -s "public/patrimonios.json" ] || exit 1

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add public/patrimonios.json
          git commit -m "🔄 Update data" || exit 0
          git push

  deploy:
    needs: sync
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: 'public'
      - uses: actions/deploy-pages@v2
