name: Sync Gist Data

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Atualiza a cada 5 minutos

permissions:
  contents: write  # Permissão para escrever no repositório

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Gist Data
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}  # Token com permissão gist
          GIST_ID: "df6ceeb52f594b01a16495b214d93af0"
        run: |
          # Baixa os dados do Gist
          curl -s -H "Authorization: token $GH_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/gists/$GIST_ID" > gist_data.json
          
          # Extrai o conteúdo e salva como patrimonios.json
          jq -r '.files."patrimonios.json".content' gist_data.json > patrimonios.json
          
          # Verificação crítica
          if [ ! -s "patrimonios.json" ]; then
            echo "::error::❌ Falha ao gerar patrimonios.json"
            exit 1
          fi

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add patrimonios.json
          git commit -m "🔄 Atualiza dados do Gist" || echo "✅ Sem alterações"
          git push
