name: Sync Gist and Deploy

on:
  schedule:
    - cron: '*/5 * * * *'  # Atualiza a cada 5 minutos
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write
  gists: read

jobs:
  sync-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Gist Data
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GIST_ID: "df6ceeb52f594b01a16495b214d93af0"
        run: |
          mkdir -p public
          curl -s -H "Authorization: token $GH_TOKEN" \
               "https://api.github.com/gists/$GIST_ID" | \
          jq -r '.files."patrimonios.json".content' > public/patrimonios.json

          # Validação do JSON
          if ! jq empty public/patrimonios.json; then
            echo "::error::Invalid JSON"
            exit 1
          fi

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add public/patrimonios.json
          git commit -m "🔄 Update data from Gist" || exit 0
          git push

  deploy:
    needs: sync-data
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: 'public'
      - uses: actions/deploy-pages@v2
        id: deployment
