name: Update Patrimônios Data

on:
  schedule:
    # Executa a cada hora (ajuste conforme necessário)
    - cron: '0 * * * *'
  workflow_dispatch: # Permite acionar manualmente

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Fetch and update data
      run: |
        # Aqui você coloca o script que atualiza os dados
        # Pode ser uma chamada a API, consulta a banco de dados, etc.
        # Exemplo fictício:
        curl -s "https://sua-api.com/patrimonios" > patrimonios.json
        
        # Configura o git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Faz commit e push das mudanças
        git add patrimonios.json
        git commit -m "🔄 Atualiza dados do patrimônio automático"
        git push
